import { headers, cookies } from "next/headers";
import { Disclaimer } from "@/components/Disclaimer";
import { NavBar } from "@/components/NavBar";
import { resolveLocale, LOCALE_COOKIE } from "@/lib/i18n";
import { DEFAULT_LOCALE } from "@/lib/config";

export const dynamic = "force-dynamic";

const T = {
  en: {
    title: "About Shui",
    p1: "Shui is a free, AI-assisted personal energy cycle analysis tool. We translate classical environmental algorithms and temporal philosophy into modern energy cycle insights — chronobiological rhythms, seasonal resonance, and spatial harmony strategies.",
    p2: "All analyses are generated by large language models based on classical references (San Ming Tong Hui and Zi Ping Zhen Quan). They are NOT predictions, advice, or guarantees. Think of them as 'weather forecasts' for your personal energy levels.",
    p3: "The site is free to use. We may earn a small affiliate commission when you purchase recommended resources — this never affects the analysis itself.",
    stack: "Tech Stack",
    license: "License: TBD (open source under consideration)",
  },
  "zh-CN": {
    title: "关于水 · 节律",
    p1: "水 · 节律是一个免费的 AI 个人能量周期分析工具。我们将经典环境算法与传统节律哲学转化为现代能量周期洞察——时间生物节律、季节共振与空间调和策略。",
    p2: "所有分析由大语言模型基于经典参考（三命通会、子平真诠）生成。它们不是预测、建议或保证。可以将其视为个人能量水平的「天气预报」。",
    p3: "本站免费使用。当你通过我们购买推荐资源时，我们可能获得少量联盟佣金——这不会影响分析本身。",
    stack: "技术栈",
    license: "许可证：待定（考虑开源）",
  },
} as const;

export default async function AboutPage({ searchParams }: { searchParams: Promise<{ lang?: string }> }) {
  const al = (await headers()).get("accept-language");
  const cookieStore = await cookies();
  const cookieLang = cookieStore.get(LOCALE_COOKIE)?.value ?? null;
  const { lang } = await searchParams;
  const locale = resolveLocale(al, cookieLang, lang, DEFAULT_LOCALE);
  const t = T[locale];

  return (
    <>
      <NavBar locale={locale} />
      <main className="container mx-auto min-h-screen px-5 py-8 sm:px-4 sm:py-12">
      <div className="mx-auto max-w-2xl space-y-6">
        <Disclaimer variant="banner" locale={locale} />
        <h1 className="text-3xl font-bold text-zinc-900 dark:text-zinc-100">
          {t.title}
        </h1>
        <div className="space-y-4 text-zinc-700 dark:text-zinc-300">
          <p>{t.p1}</p>
          <p>{t.p2}</p>
          <p>{t.p3}</p>
        </div>
        <div className="rounded-lg border border-zinc-200 bg-white/60 p-4 dark:border-zinc-800 dark:bg-zinc-900/40">
          <div className="text-sm font-medium text-zinc-500 dark:text-zinc-400">
            {t.stack}
          </div>
          <div className="mt-2 text-sm text-zinc-700 dark:text-zinc-300">
            Next.js 14 · TypeScript 5 · Tailwind CSS · SQLite · Zhipu GLM-4-Flash · NVIDIA NIM
          </div>
        </div>
        <p className="text-xs text-zinc-500 dark:text-zinc-400">{t.license}</p>
        <Disclaimer variant="inline" locale={locale} />
      </div>
    </main>
    </>
  );
}
