import type { FateAnalysis } from "@/lib/fate-analysis";
import {
  formatBaziString,
  formatDayMaster,
  formatFavorableElements,
  formatStrengthLabel,
} from "@/lib/bazi/i18n-terms";
import { getStylePreset } from "@/lib/settings";

type Locale = "en" | "zh-CN";

interface PdfReportData {
  id: string;
  locale: Locale;
  content: string;
  analysis: FateAnalysis;
  ai: { provider: string | null; model: string | null };
  fateBook: string;
  tier: string;
  createdAt: number;
  recommendations: Array<{
    title: string;
    description: string | null;
    category: string;
    url: string;
    price: string | null;
    matchReasons: string[];
  }>;
  theme?: string;
  icon?: string;
  columns?: number;
}

export type { PdfReportData, Locale };

type CardTheme = "indigo" | "dark" | "warm" | "glass";

const WX_NAME: Record<string, Record<Locale, string>> = {
  wood: { en: "Wood", "zh-CN": "木" },
  fire: { en: "Fire", "zh-CN": "火" },
  earth: { en: "Earth", "zh-CN": "土" },
  metal: { en: "Metal", "zh-CN": "金" },
  water: { en: "Water", "zh-CN": "水" },
};

const WX_COLOR: Record<string, string> = {
  wood: "#10B981", fire: "#EF4444", earth: "#F59E0B",
  metal: "#6B7280", water: "#3B82F6",
};

type Labels = {
  brand: string; subtitle: string; reportTitle: string; premiumTitle: string;
  reportId: string; bazi: string; wuxing: string; dayMaster: string;
  strength: string; favorable: string; unfavorable: string; aiMeta: string;
  classic: string; disclaimer: string; inDepth: string;
};

const T: Record<Locale, Labels> = {
  en: {
    brand: "Shui", subtitle: "Decode Your Personal Energy Cycle",
    reportTitle: "Personal Energy Cycle Report", premiumTitle: "In-Depth Energy Profile",
    reportId: "Report ID", bazi: "Temporal Energy Vector", wuxing: "Elemental Balance",
    dayMaster: "Core Element", strength: "Energy Level", favorable: "Energy Catalysts",
    unfavorable: "Elements to Observe", aiMeta: "Powered by Shui Algorithmic Engine", classic: "Classic",
    disclaimer: "This reference report is generated by the Shui Chronobiological Algorithmic Engine based on classical temporal logic and environmental harmony principles. It is provided for personal reflection and educational purposes only, and does not constitute medical, investment, marital, career, legal, or any other form of decision-making advice. Data auto-purged in 24h.",
    inDepth: "In-Depth",
  },
  "zh-CN": {
    brand: "水 · 节律", subtitle: "解码你的个人能量周期",
    reportTitle: "个人能量周期报告", premiumTitle: "深度能量节律图谱",
    reportId: "报告编号", bazi: "时间能量向量", wuxing: "五行平衡",
    dayMaster: "核心元素", strength: "能量水平", favorable: "能量催化剂",
    unfavorable: "需关注元素", aiMeta: "由水·节律算法引擎驱动", classic: "典籍",
    disclaimer: "本参考报告由水·节律时间生物算法引擎基于经典时序逻辑与环境调和原理生成，仅供个人参考与教育用途，不构成医疗、投资、婚恋、职业、法律等任何领域的决策建议。数据 24 小时自动清除。",
    inDepth: "深度版",
  },
} as const;

interface ThemeConfig {
  vars: Record<string, string>;
  bodyBg: string;
  needsGradient: boolean;
}

const THEMES: Record<CardTheme, ThemeConfig> = {
  indigo: {
    vars: {
      "cover-bg": "#F5F3FF", "cover-bar": "#4F46E5", "brand": "#4F46E5",
      "title": "#1F2937", "text": "#374151", "muted": "#6B7280",
      "bg": "#F9FAFB", "paper": "#FFFFFF", "border": "#E5E7EB",
      "bar-bg": "#F3F4F6", "divider": "#E5E7EB", "pillar-bg": "#EEF2FF",
      "premium": "#D97706",
    },
    bodyBg: "#FFFFFF",
    needsGradient: false,
  },
  dark: {
    vars: {
      "cover-bg": "#0F0F11", "cover-bar": "#818CF8", "brand": "#A5B4FC",
      "title": "#E0E7FF", "text": "#E0E7FF", "muted": "rgba(224,231,255,0.6)",
      "bg": "#1E1B4B", "paper": "#1A1744", "border": "#3730A3",
      "bar-bg": "#312E81", "divider": "rgba(255,255,255,0.15)", "pillar-bg": "#312E81",
      "premium": "#FCD34D",
    },
    bodyBg: "#1E1B4B",
    needsGradient: false,
  },
  warm: {
    vars: {
      "cover-bg": "#1C1917", "cover-bar": "#F59E0B", "brand": "#FDE68A",
      "title": "#FDE68A", "text": "#FDE68A", "muted": "rgba(253,230,138,0.6)",
      "bg": "#292524", "paper": "#231F1D", "border": "#D97706",
      "bar-bg": "#78350F", "divider": "rgba(255,255,255,0.12)", "pillar-bg": "#3F2A1A",
      "premium": "#FBBF24",
    },
    bodyBg: "#292524",
    needsGradient: false,
  },
  glass: {
    vars: {
      "cover-bg": "linear-gradient(135deg, #667EEA, #764BA2)",
      "cover-bar": "#FFFFFF", "brand": "#FFFFFF",
      "title": "#FFFFFF", "text": "#FFFFFF", "muted": "rgba(255,255,255,0.75)",
      "bg": "rgba(255,255,255,0.06)", "paper": "rgba(255,255,255,0.10)",
      "border": "rgba(255,255,255,0.25)", "bar-bg": "rgba(255,255,255,0.12)",
      "divider": "rgba(255,255,255,0.2)", "pillar-bg": "rgba(255,255,255,0.10)",
      "premium": "#FDE68A",
    },
    bodyBg: "linear-gradient(135deg, #667EEA, #764BA2)",
    needsGradient: true,
  },
};

function cssVars(vars: Record<string, string>): string {
  return Object.entries(vars).map(([k, v]) => `--${k}:${v};`).join("");
}

function iconSvg(icon: string, brandColor: string): string {
  if (icon === "moon") {
    return `<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%">
      <circle cx="100" cy="100" r="85" fill="none" stroke="${brandColor}" stroke-width="1" opacity="0.2"/>
      <circle cx="100" cy="100" r="65" fill="${brandColor}" opacity="0.9"/>
      <circle cx="125" cy="100" r="65" fill="var(--cover-bg-solid, #667EEA)"/>
      <circle cx="50" cy="60" r="2" fill="${brandColor}" opacity="0.6"/>
      <circle cx="150" cy="50" r="1.5" fill="${brandColor}" opacity="0.5"/>
      <circle cx="40" cy="140" r="1.5" fill="${brandColor}" opacity="0.5"/>
      <circle cx="160" cy="140" r="2" fill="${brandColor}" opacity="0.6"/>
    </svg>`;
  }
  return `<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:100%">
    <circle cx="100" cy="100" r="85" fill="none" stroke="${brandColor}" stroke-width="1" opacity="0.2"/>
    <circle cx="100" cy="30" r="14" fill="#10B981" opacity="0.9"/>
    <circle cx="165" cy="70" r="14" fill="#EF4444" opacity="0.9"/>
    <circle cx="140" cy="150" r="14" fill="#F59E0B" opacity="0.9"/>
    <circle cx="60" cy="150" r="14" fill="#6B7280" opacity="0.9"/>
    <circle cx="35" cy="70" r="14" fill="#3B82F6" opacity="0.9"/>
    <path d="M100 30L165 70L140 150L60 150L35 70Z" fill="none" stroke="${brandColor}" stroke-width="1.5" opacity="0.3" stroke-dasharray="4,4"/>
    <circle cx="100" cy="100" r="6" fill="${brandColor}" opacity="0.6"/>
  </svg>`;
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function parseContent(content: string): string {
  const lines = content.split("\n");
  const htmlParts: string[] = [];
  let inUl = false;
  let inOl = false;

  function closeLists() {
    if (inUl) { htmlParts.push("</ul>"); inUl = false; }
    if (inOl) { htmlParts.push("</ol>"); inOl = false; }
  }

  function inlineFormat(text: string): string {
    let result = esc(text);
    result = result.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
    result = result.replace(/\*(.+?)\*/g, "<em>$1</em>");
    result = result.replace(/`(.+?)`/g, "<code>$1</code>");
    return result;
  }

  for (const rawLine of lines) {
    const t = rawLine.trim();
    if (!t) { closeLists(); continue; }

    if (t.startsWith("### ")) {
      closeLists();
      htmlParts.push(`<h3>${inlineFormat(t.slice(4))}</h3>`);
    } else if (t.startsWith("## ")) {
      closeLists();
      htmlParts.push(`<h2>${inlineFormat(t.slice(3))}</h2>`);
    } else if (t.startsWith("# ")) {
      closeLists();
      htmlParts.push(`<h1>${inlineFormat(t.slice(2))}</h1>`);
    } else if (t.match(/^(\d+)\.\s/)) {
      if (inUl) { htmlParts.push("</ul>"); inUl = false; }
      if (!inOl) { htmlParts.push("<ol>"); inOl = true; }
      const content = t.replace(/^\d+\.\s/, "");
      htmlParts.push(`<li>${inlineFormat(content)}</li>`);
    } else if (t.startsWith("- ") || t.startsWith("* ")) {
      if (inOl) { htmlParts.push("</ol>"); inOl = false; }
      if (!inUl) { htmlParts.push("<ul>"); inUl = true; }
      htmlParts.push(`<li>${inlineFormat(t.slice(2))}</li>`);
    } else if (t.startsWith("---") || t.startsWith("***")) {
      closeLists();
      htmlParts.push("<hr>");
    } else {
      closeLists();
      htmlParts.push(`<p>${inlineFormat(t)}</p>`);
    }
  }
  closeLists();
  return htmlParts.join("\n");
}

const SHARED_CSS = `
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: 'Noto Sans SC', 'SimHei', 'Microsoft YaHei', sans-serif;
  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;
  background: var(--body-bg);
  color: var(--text);
  display: flex;
  flex-direction: column;
  align-items: center;
}

.page {
  width: 210mm;
  min-height: 297mm;
  background: var(--paper);
  position: relative;
  page-break-after: always;
  padding: 0;
  margin-bottom: 0;
  box-shadow: 0 2px 16px rgba(0,0,0,0.12);
}

.cover {
  background: var(--cover-bg);
  display: flex;
  flex-direction: column;
  min-height: 297mm;
  height: 297mm;
}
.cover-top-bar { height: 6px; background: var(--cover-bar); flex-shrink: 0; }
.cover-art-area { flex: 0 0 auto; padding: 48px 60px 0; display: flex; justify-content: center; }
.cover-art { width: 160px; height: 160px; border-radius: 50%; display: flex; align-items: center; justify-content: center; }
.cover-center { flex: 1; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; padding: 20px 60px; }
.cover-brand { font-size: 36px; font-weight: 700; color: var(--brand); letter-spacing: 6px; margin-bottom: 8px; }
.cover-subtitle { font-size: 13px; color: var(--muted); letter-spacing: 2px; margin-bottom: 32px; }
.cover-title { font-size: 24px; font-weight: 700; color: var(--title); letter-spacing: 2px; margin-bottom: 16px; }
.cover-premium { display: inline-flex; align-items: center; gap: 6px; font-size: 12px; color: var(--premium); border: 1px solid var(--premium); padding: 5px 16px; border-radius: 20px; margin-bottom: 28px; font-weight: 600; }
.cover-bazi { font-size: 11px; color: var(--muted); letter-spacing: 3px; margin-bottom: 10px; }
.cover-meta { font-size: 10px; color: var(--muted); margin-bottom: 4px; letter-spacing: 1px; }
.cover-footer { padding: 20px 60px 28px; flex-shrink: 0; }
.cover-divider { height: 1px; background: var(--divider); margin-bottom: 14px; }
.cover-copyright { font-size: 8px; color: var(--muted); text-align: center; letter-spacing: 1px; }

.analysis { padding: 44px 56px; background: var(--bg); display: flex; flex-direction: column; min-height: 297mm; }
.analysis-header { display: flex; justify-content: space-between; align-items: flex-end; padding-bottom: 16px; border-bottom: 1px solid var(--divider); margin-bottom: 24px; }
.analysis-brand { font-size: 14px; font-weight: 700; color: var(--brand); letter-spacing: 2px; }
.analysis-id { font-size: 9px; color: var(--muted); text-align: right; letter-spacing: 1px; }
.section-title { font-size: 16px; font-weight: 700; color: var(--brand); margin-bottom: 16px; display: flex; align-items: baseline; gap: 10px; }
.section-title-en { font-size: 9px; color: var(--muted); letter-spacing: 2px; font-weight: 400; }
.pillars { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin-bottom: 28px; }
.pillar { background: var(--pillar-bg); border: 1px solid var(--border); border-radius: 10px; padding: 14px 8px; text-align: center; }
.pillar-label { font-size: 9px; color: var(--muted); letter-spacing: 2px; margin-bottom: 6px; }
.pillar-value { font-size: 20px; font-weight: 700; color: var(--brand); letter-spacing: 1px; }
.wuxing-row { display: grid; grid-template-columns: 70px 1fr 40px; align-items: center; gap: 12px; margin-bottom: 10px; }
.wuxing-label { font-size: 10px; color: var(--text); font-weight: 600; display: flex; align-items: center; gap: 8px; }
.wuxing-dot { width: 8px; height: 8px; border-radius: 50%; display: inline-block; }
.wuxing-bar-wrap { height: 12px; background: var(--bar-bg); border-radius: 6px; overflow: hidden; }
.wuxing-bar-fill { height: 100%; border-radius: 6px; }
.wuxing-percent { font-size: 10px; color: var(--muted); text-align: right; font-weight: 700; }
.core-section { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; padding: 18px; background: var(--paper); border: 1px solid var(--border); border-radius: 12px; margin-top: 24px; }
.core-item { display: flex; flex-direction: column; gap: 4px; }
.core-label { font-size: 9px; color: var(--muted); letter-spacing: 1px; }
.core-value { font-size: 12px; color: var(--text); font-weight: 600; }
.core-value.highlight { color: var(--brand); font-size: 15px; }

.content-page { padding: 36px 56px 48px; background: var(--paper); }
.content-header { display: flex; justify-content: space-between; align-items: center; padding-bottom: 10px; border-bottom: 1px solid var(--divider); margin-bottom: 16px; }
.content-header-left { font-size: 10px; color: var(--muted); letter-spacing: 2px; }
.content-body { column-count: var(--content-columns, 2); column-gap: 24px; column-rule: 1px solid var(--divider); }
.content-body h1 { font-size: 14px; font-weight: 700; color: var(--brand); margin-top: 12px; margin-bottom: 8px; padding-bottom: 5px; border-bottom: 1px solid var(--divider); letter-spacing: 1px; column-span: none; break-after: avoid; }
.content-body h2 { font-size: 12px; font-weight: 700; color: var(--brand); margin-top: 10px; margin-bottom: 5px; break-after: avoid; }
.content-body h3 { font-size: 11px; font-weight: 700; color: var(--brand); margin-top: 8px; margin-bottom: 4px; break-after: avoid; }
.content-body p { font-size: 9px; color: var(--text); line-height: 1.7; margin-bottom: 6px; text-align: justify; }
.content-body ul, .content-body ol { margin-bottom: 8px; }
.content-body li { font-size: 9px; color: var(--text); line-height: 1.65; padding-left: 12px; position: relative; margin-bottom: 3px; break-inside: avoid; }
.content-body li::before { content: '\\2022'; position: absolute; left: 0; color: var(--brand); font-weight: 700; font-size: 10px; }
.content-body ol li::before { content: counters(list-item, '.') '.'; position: absolute; left: 0; color: var(--brand); font-weight: 600; font-size: 9px; }
.content-body strong { font-weight: 700; color: var(--title); }
.content-body em { font-style: italic; }
.content-body code { font-family: monospace; font-size: 8px; background: var(--bar-bg); padding: 1px 4px; border-radius: 3px; }
.content-body hr { height: 1px; background: var(--divider); border: none; margin: 10px 0; }

.disclaimer-page { padding: 48px 56px; background: var(--bg); display: flex; flex-direction: column; justify-content: flex-end; min-height: 297mm; }
.disclaimer-top { flex: 1; display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; }
.disclaimer-mark { font-size: 80px; font-weight: 700; color: var(--brand); opacity: 0.12; letter-spacing: 8px; }
.disclaimer-end-title { font-size: 18px; font-weight: 700; color: var(--title); letter-spacing: 4px; margin-bottom: 8px; }
.disclaimer-end-sub { font-size: 10px; color: var(--muted); letter-spacing: 2px; }
.disclaimer-divider { height: 1px; background: var(--divider); margin: 40px 0 20px; }
.disclaimer-text { font-size: 10px; color: var(--muted); line-height: 1.7; margin-bottom: 30px; text-align: justify; }
.disclaimer-copyright { font-size: 8px; color: var(--muted); text-align: center; letter-spacing: 1px; line-height: 1.8; }

@media print {
  .no-print { display: none !important; }
  body { background: none; display: block; }
  .page { page-break-after: always; box-shadow: none; }
}
`;

export function buildHtml(data: PdfReportData): string {
  const themeSetting = data.theme || getStylePreset().theme;
  const theme: CardTheme = THEMES[themeSetting as CardTheme] ? (themeSetting as CardTheme) : "indigo";
  const icon = data.icon || "wuxing";
  const t = T[data.locale];
  const isPremium = data.tier === "premium";
  const themeConfig = THEMES[theme];
  const brandColor = themeConfig.vars["brand"];

  const baziFormatted = formatBaziString(data.analysis.bazi, data.locale);
  const dateStr = new Date(data.createdAt).toISOString().split("T")[0];
  const aiLabel = `${t.aiMeta}`;
  const year = new Date(data.createdAt).getFullYear();

  const dmFormatted = formatDayMaster(data.analysis.dayMaster, data.locale);
  const strFormatted = formatStrengthLabel(data.analysis.dayMasterStrength, data.locale);
  const favFormatted = formatFavorableElements(data.analysis.favorableElements, data.locale);
  const unfavFormatted = formatFavorableElements(data.analysis.unfavorableElements, data.locale);

  const wxEntries = Object.entries(data.analysis.wuxing) as [string, number][];
  const wxSum = wxEntries.reduce((s, [, v]) => s + v, 0) || 1;

  const pillarLabels = data.locale === "zh-CN"
    ? ["\u5E74\u67F1", "\u6708\u67F1", "\u65E5\u67F1", "\u65F6\u67F1"]
    : ["Year", "Month", "Day", "Hour"];

  const wuxingRows = wxEntries.map(([k, v]) => {
    const name = WX_NAME[k]?.[data.locale] ?? k;
    const color = WX_COLOR[k] ?? brandColor;
    const pct = Math.round((v / wxSum) * 100);
    return `<div class="wuxing-row">
      <div class="wuxing-label"><span class="wuxing-dot" style="background:${color}"></span>${esc(name)}</div>
      <div class="wuxing-bar-wrap"><div class="wuxing-bar-fill" style="width:${pct}%;background:${color}"></div></div>
      <div class="wuxing-percent">${v}%</div>
    </div>`;
  }).join("\n");

  const pillarsHtml = baziFormatted.map((p: string, i: number) =>
    `<div class="pillar"><div class="pillar-label">${pillarLabels[i]}</div><div class="pillar-value">${esc(p)}</div></div>`
  ).join("\n");

  const contentHtml = parseContent(data.content);
  const columns = data.columns ?? 2;

  const coverBgStyle = themeConfig.needsGradient
    ? `background: ${themeConfig.vars["cover-bg"]};`
    : `background: var(--cover-bg);`;

  const bodyBgStyle = themeConfig.needsGradient
    ? `background: ${themeConfig.bodyBg}; background-attachment: fixed;`
    : `background: var(--body-bg);`;

  const pageBgStyle = themeConfig.needsGradient
    ? `background: ${themeConfig.bodyBg};`
    : "";

  const coverBgSolid = themeConfig.needsGradient ? "#764BA2" : themeConfig.vars["cover-bg"];

  return `<!DOCTYPE html>
<html lang="${data.locale === "zh-CN" ? "zh-CN" : "en"}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
@import url('https://cdn.jsdelivr.net/npm/@fontsource/noto-sans-sc@5.0.0/400.css');
@import url('https://cdn.jsdelivr.net/npm/@fontsource/noto-sans-sc@5.0.0/700.css');

:root {
  ${cssVars(themeConfig.vars)}
  --body-bg: ${themeConfig.bodyBg};
  --cover-bg-solid: ${coverBgSolid};
  --content-columns: ${columns};
}
${SHARED_CSS}
</style>
</head>
<body style="${bodyBgStyle}">

<div class="page cover" style="${coverBgStyle}">
  <div class="cover-top-bar"></div>
  <div class="cover-art-area"><div class="cover-art">${iconSvg(icon, brandColor)}</div></div>
  <div class="cover-center">
    <div class="cover-brand">${esc(t.brand)}</div>
    <div class="cover-subtitle">${esc(t.subtitle)}</div>
    <div class="cover-title">${esc(isPremium ? t.premiumTitle : t.reportTitle)}</div>
    ${isPremium ? `<div class="cover-premium">\u2726 ${esc(t.inDepth)}</div>` : ""}
    <div class="cover-bazi">${baziFormatted.map(esc).join(" \u00B7 ")}</div>
    <div class="cover-meta">${esc(t.reportId)}: ${data.id.slice(0, 8)} \u00B7 ${dateStr}</div>
    <div class="cover-meta">${esc(aiLabel)}</div>
  </div>
  <div class="cover-footer">
    <div class="cover-divider"></div>
    <div class="cover-copyright">\u00A9 ${year} Shui by AEOX (YAOLUMEN TECHNOLOGIES LTD)</div>
  </div>
</div>

<div class="page analysis" style="${pageBgStyle}">
  <div class="analysis-header">
    <div><div class="analysis-brand">${esc(t.brand)}</div></div>
    <div class="analysis-id">${data.id.slice(0, 8)}<br>${dateStr}</div>
  </div>
  <div class="section-title">${esc(t.bazi)} <span class="section-title-en">${esc(t.wuxing)}</span></div>
  <div class="pillars">${pillarsHtml}</div>
  <div class="section-title">${esc(t.wuxing)}</div>
  ${wuxingRows}
  <div class="core-section">
    <div class="core-item"><div class="core-label">${esc(t.dayMaster)}</div><div class="core-value highlight">${esc(dmFormatted)}</div></div>
    <div class="core-item"><div class="core-label">${esc(t.strength)}</div><div class="core-value">${esc(strFormatted)}</div></div>
    <div class="core-item"><div class="core-label">${esc(t.favorable)}</div><div class="core-value">${esc(favFormatted)}</div></div>
    <div class="core-item"><div class="core-label">${esc(t.unfavorable)}</div><div class="core-value">${esc(unfavFormatted)}</div></div>
  </div>
</div>

<div class="page content-page" style="${pageBgStyle}">
  <div class="content-header"><div class="content-header-left">${esc(t.brand)} \u00B7 ${isPremium ? esc(t.inDepth) : "Report"}</div></div>
  <div class="content-body">
    ${contentHtml}
  </div>
</div>

<div class="page disclaimer-page" style="${pageBgStyle}">
  <div class="disclaimer-top">
    <div class="disclaimer-mark">${data.locale === "zh-CN" ? "\u8282\u5F8B" : "Shui"}</div>
    <div class="disclaimer-end-title">${data.locale === "zh-CN" ? "\u62A5\u544A\u7ED3\u675F" : "End of Report"}</div>
    <div class="disclaimer-end-sub">${data.locale === "zh-CN" ? "" : "END OF REPORT"}</div>
  </div>
  <div class="disclaimer-divider"></div>
  <div class="disclaimer-text">${esc(t.disclaimer)}</div>
  <div class="disclaimer-copyright">\u00A9 ${new Date().getFullYear()} Shui by AEOX (YAOLUMEN TECHNOLOGIES LTD). All rights reserved.</div>
</div>

</body>
</html>`;
}
