import { cn } from "@/lib/utils";

interface DisclaimerProps {
  className?: string;
  variant?: "banner" | "inline" | "compact";
  locale?: "zh-CN" | "en";
}

const COPY = {
  "zh-CN": {
    short: "基于传统节律文化，仅供个人成长与正念参考，不构成任何决策建议。数据 24 小时自动清除。",
    long: "本平台运用经典环境算法与传统节律哲学，提供个人成长、室内美学指导与正念参考。本参考报告由水·节律时间生物算法引擎基于经典时序逻辑与环境调和原理生成，仅供个人参考与教育用途，不构成医疗、投资、婚恋、职业、法律等任何领域的决策建议。我们实行零知识数据政策：您的出生信息仅在实时内存中用于计算，报告生成后 24 小时内自动清除。您的生命由自己的选择塑造。",
    affiliate: "本报告中的部分产品链接为联盟营销链接。如果您通过这些链接购买，我们可能获得小额佣金，不增加您的任何费用。我们仅推荐与您的空间能量建议一致的产品。",
    dataLifecycle: "隐私优先：您的出生信息仅在实时内存中用于计算能量图谱，报告生成后 24 小时内自动从服务器清除。请及时下载或保存您的报告。",
  },
  en: {
    short: "Science-informed insights for personal growth & mindfulness only. Not advice. Data auto-purged in 24h.",
    long: "This platform utilizes classical environmental algorithms and temporal philosophy to offer personal growth, interior aesthetic guidance, and mindfulness insights. This reference report is generated by the Shui Chronobiological Algorithmic Engine based on classical temporal logic and environmental harmony principles. It is provided for personal reflection and educational purposes only, and does NOT constitute medical, investment, marital, career, legal, or any other form of decision-making advice. We enforce a strict Zero-Knowledge Data Policy: your birth details are held in temporary memory only to compute your analysis and are automatically purged within 24 hours. Your life is shaped by your own choices.",
    affiliate: "Some of the product links provided in our reports and recommendations are affiliate links. If you purchase through these links, we may earn a small commission at no additional cost to you. We only recommend items that align with your spatial energy recommendations.",
    dataLifecycle: "Privacy by Design: Your birth details are held in temporary server memory only to render your analysis and are automatically purged within 24 hours. We strongly recommend downloading or saving your report immediately after viewing.",
  },
} as const;

export function Disclaimer({
  className,
  variant = "banner",
  locale = "en",
}: DisclaimerProps) {
  const t = COPY[locale];
  if (variant === "banner") {
    return (
      <div
        className={cn(
          "rounded-lg border border-amber-200 bg-amber-50/80 px-4 py-3 text-sm text-amber-900",
          "dark:border-amber-900/50 dark:bg-amber-950/30 dark:text-amber-200",
          className
        )}
        role="note"
        aria-label="disclaimer"
      >
        {t.short}
      </div>
    );
  }
  if (variant === "inline") {
    return (
      <p
        className={cn(
          "text-xs text-zinc-500 dark:zinc-500",
          className
        )}
      >
        {t.short}
      </p>
    );
  }
  return (
    <details
      className={cn(
        "rounded-lg border border-zinc-200 bg-zinc-50/50 p-3 text-xs text-zinc-600",
        "dark:border-zinc-800 dark:bg-zinc-900/50 dark:text-zinc-400",
        className
      )}
    >
      <summary className="cursor-pointer font-medium">
        {locale === "zh-CN" ? "完整免责与合规声明" : "Full Disclaimer & Compliance"}
      </summary>
      <div className="mt-3 space-y-3 leading-relaxed">
        <div>
          <h4 className="font-semibold text-zinc-700 dark:text-zinc-300">
            {locale === "zh-CN" ? "服务性质声明" : "Service Disclaimer"}
          </h4>
          <p className="mt-1">{t.long}</p>
        </div>
        <div>
          <h4 className="font-semibold text-zinc-700 dark:text-zinc-300">
            {locale === "zh-CN" ? "联盟营销透明声明" : "Affiliate Disclosure"}
          </h4>
          <p className="mt-1">{t.affiliate}</p>
        </div>
        <div>
          <h4 className="font-semibold text-zinc-700 dark:text-zinc-300">
            {locale === "zh-CN" ? "数据生命周期" : "Data Lifecycle Notice"}
          </h4>
          <p className="mt-1">{t.dataLifecycle}</p>
        </div>
      </div>
    </details>
  );
}
