import { headers, cookies } from "next/headers";
import { NavBar } from "@/components/NavBar";
import { resolveLocale, LOCALE_COOKIE } from "@/lib/i18n";
import { DEFAULT_LOCALE } from "@/lib/config";

export const dynamic = "force-dynamic";

const T = {
  en: { title: "Terms of Use", effective: "Effective: 2026-08-15" },
  "zh-CN": { title: "使用条款", effective: "生效日期：2026-08-15" },
} as const;

const BODY = {
  en: [
    "1. No advice. The content on this platform is generated by AI based on classical environmental algorithms and temporal philosophy. It is for personal growth, interior aesthetic guidance, and mindfulness reference only. It does NOT constitute medical, investment, marital, career, legal, or any other form of decision-making advice.",
    "2. No guarantees. AI-generated content is heuristic and may contain errors. Do not rely on it for important life decisions. Future outcomes depend on individual choices, actions, and real-world conditions — our reports do not predict fixed outcomes.",
    "3. Fair use. The free analysis service is rate-limited to 10 generations per hour per IP address. Abuse will be blocked.",
    "4. Digital content. Because digital reports and downloadable PDF guides are instantly generated and delivered upon purchase, all sales of digital content are final. If you experience technical issues receiving your PDF, our support team will assist you in regenerating your document promptly.",
    "5. Affiliates. Recommended resource links may earn the site operator a small commission at no additional cost to you. This does not influence the generated analysis. We only recommend items that align with your spatial energy recommendations.",
    "6. No warranty. The site is provided as-is, without warranty of any kind.",
    "7. Changes. These terms may be updated. Continued use indicates acceptance.",
    "8. Age Restriction. You must be at least 18 years old (or the age of majority in your jurisdiction) to use this platform. If you are under 18, you may only use this site under the supervision of a parent or legal guardian.",
    "9. Limitation of Liability. To the maximum extent permitted by applicable law, Shui and its operators shall not be liable for any indirect, incidental, or consequential damages resulting from your use of the AI-generated reference reports. Our total aggregate liability for any claims arising hereunder shall not exceed the amount you paid to us (if any) in the past 30 days.",
    "10. Governing Law & Jurisdiction. These Terms shall be governed by and construed in accordance with the laws of England and Wales. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts of England and Wales.",
  ],
  "zh-CN": [
    "1. 非建议。本平台内容由 AI 基于经典环境算法与传统节律哲学生成，仅供个人成长、室内美学指导与正念参考，不构成医疗、投资、婚恋、职业、法律等任何领域的决策建议。",
    "2. 无保证。AI 生成的内容是启发性的，可能存在错误。请勿据此做出重大人生决定。未来结果取决于个人选择、行动和现实条件——我们的报告不预测固定结果。",
    "3. 合理使用。免费分析服务每个 IP 每小时限 10 次。滥用将被拦截。",
    "4. 数字内容。由于数字报告和可下载 PDF 指南在购买后即时生成和交付，所有数字内容的销售均为最终销售。但如果你在接收 PDF 时遇到技术问题，我们的支持团队将协助你重新生成文档。",
    "5. 联盟推广。推荐资源链接可能为本站运营者带来小额佣金，不增加您的费用。这不会影响生成的分析内容。我们仅推荐与您的空间能量建议一致的产品。",
    "6. 无担保。本站按「现状」提供，不作任何形式的担保。",
    "7. 变更。这些条款可能会更新。继续使用即视为接受。",
    "8. 年龄限制。您必须年满 18 周岁（或您所在司法管辖区的法定成年年龄）方可使用本平台。未满 18 周岁者须在父母或法定监护人监督下使用本站。",
    "9. 责任限制。在适用法律允许的最大范围内，Shui 及其运营方不对您因使用 AI 生成的参考报告而导致的任何间接、附带或后果性损害承担责任。我们因本条款产生的任何索赔的总累计责任不超过您在过去 30 天内向我们支付的金额（如有）。",
    "10. 管辖法律与司法管辖权。本条款受英格兰和威尔士法律管辖并据其解释。因本条款产生的任何争议应提交英格兰和威尔士法院的专属管辖。",
  ],
} as const;

export default async function TermsPage({ searchParams }: { searchParams: Promise<{ lang?: string }> }) {
  const al = (await headers()).get("accept-language");
  const cookieStore = await cookies();
  const cookieLang = cookieStore.get(LOCALE_COOKIE)?.value ?? null;
  const { lang } = await searchParams;
  const locale = resolveLocale(al, cookieLang, lang, DEFAULT_LOCALE);
  const t = T[locale];
  const body = BODY[locale];

  return (
    <>
      <NavBar locale={locale} />
      <main className="container mx-auto min-h-screen px-5 py-8 sm:px-4 sm:py-12">
      <div className="mx-auto max-w-2xl space-y-4">
        <h1 className="text-3xl font-bold text-zinc-900 dark:text-zinc-100">
          {t.title}
        </h1>
        <p className="text-sm text-zinc-500 dark:text-zinc-400">{t.effective}</p>
        {body.map((line, i) => (
          <p
            key={i}
            className="leading-relaxed text-zinc-700 dark:text-zinc-300"
          >
            {line}
          </p>
        ))}
      </div>
    </main>
    </>
  );
}
